<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class ProdukSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */

    public function run(): void
    {
        DB::table('product')->insert([
            [
                'product_name' => 'Kaos Polos Hitam',
                'price' => 75000,
                'link' => 'https://example.com/kaos-hitam',
                'is_active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => null,
                'desc' => 'Kaos polos warna hitam bahan cotton combed',
                'deleted_at' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'product_name' => 'Kaos Polos Putih',
                'price' => 75000,
                'link' => 'https://example.com/kaos-putih',
                'is_active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => null,
                'desc' => 'Kaos polos warna putih bahan cotton combed',
                'deleted_at' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'product_name' => 'Hoodie Abu-Abu',
                'price' => 185000,
                'link' => 'https://example.com/hoodie-abu',
                'is_active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => null,
                'desc' => 'Hoodie abu-abu hangat dan nyaman',
                'deleted_at' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'product_name' => 'Hoodie Hitam',
                'price' => 190000,
                'link' => 'https://example.com/hoodie-hitam',
                'is_active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => null,
                'desc' => 'Hoodie hitam premium',
                'deleted_at' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'product_name' => 'Jaket Denim',
                'price' => 250000,
                'link' => 'https://example.com/jaket-denim',
                'is_active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => null,
                'desc' => 'Jaket denim pria casual',
                'deleted_at' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],

            [
                'product_name' => 'Kemeja Flanel Merah',
                'price' => 165000,
                'link' => 'https://example.com/flanel-merah',
                'is_active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => null,
                'desc' => 'Kemeja flanel motif kotak merah',
                'deleted_at' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'product_name' => 'Kemeja Flanel Biru',
                'price' => 165000,
                'link' => 'https://example.com/flanel-biru',
                'is_active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => null,
                'desc' => 'Kemeja flanel motif kotak biru',
                'deleted_at' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'product_name' => 'Celana Jeans Slim Fit',
                'price' => 220000,
                'link' => 'https://example.com/jeans-slim',
                'is_active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => null,
                'desc' => 'Celana jeans slim fit pria',
                'deleted_at' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'product_name' => 'Celana Chino Khaki',
                'price' => 210000,
                'link' => 'https://example.com/chino-khaki',
                'is_active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => null,
                'desc' => 'Celana chino warna khaki',
                'deleted_at' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'product_name' => 'Celana Cargo Hitam',
                'price' => 230000,
                'link' => 'https://example.com/cargo-hitam',
                'is_active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => null,
                'desc' => 'Celana cargo hitam dengan banyak kantong',
                'deleted_at' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],

            [
                'product_name' => 'Topi Baseball Hitam',
                'price' => 85000,
                'link' => 'https://example.com/topi-hitam',
                'is_active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => null,
                'desc' => 'Topi baseball warna hitam',
                'deleted_at' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'product_name' => 'Topi Trucker',
                'price' => 90000,
                'link' => 'https://example.com/topi-trucker',
                'is_active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => null,
                'desc' => 'Topi trucker casual',
                'deleted_at' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'product_name' => 'Sepatu Sneakers Putih',
                'price' => 320000,
                'link' => 'https://example.com/sneakers-putih',
                'is_active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => null,
                'desc' => 'Sneakers putih minimalis',
                'deleted_at' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'product_name' => 'Sepatu Sneakers Hitam',
                'price' => 330000,
                'link' => 'https://example.com/sneakers-hitam',
                'is_active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => null,
                'desc' => 'Sneakers hitam elegan',
                'deleted_at' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],

            [
                'product_name' => 'Sandal Casual',
                'price' => 120000,
                'link' => 'https://example.com/sandal-casual',
                'is_active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => null,
                'desc' => 'Sandal casual nyaman dipakai',
                'deleted_at' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'product_name' => 'Tas Selempang',
                'price' => 145000,
                'link' => 'https://example.com/tas-selempang',
                'is_active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => null,
                'desc' => 'Tas selempang pria',
                'deleted_at' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'product_name' => 'Tas Ransel',
                'price' => 275000,
                'link' => 'https://example.com/tas-ransel',
                'is_active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => null,
                'desc' => 'Tas ransel untuk aktivitas harian',
                'deleted_at' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'product_name' => 'Dompet Kulit',
                'price' => 98000,
                'link' => 'https://example.com/dompet-kulit',
                'is_active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => null,
                'desc' => 'Dompet kulit sintetis',
                'deleted_at' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'product_name' => 'Ikat Pinggang Kulit',
                'price' => 90000,
                'link' => 'https://example.com/ikat-pinggang',
                'is_active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => null,
                'desc' => 'Ikat pinggang bahan kulit',
                'deleted_at' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'product_name' => 'Jam Tangan Casual',
                'price' => 350000,
                'link' => 'https://example.com/jam-casual',
                'is_active' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_by' => null,
                'desc' => 'Jam tangan casual pria',
                'deleted_at' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
        ]);
    }
}
